services:

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: helsb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"

  chatbot:
    build: .
    container_name: helsb-rag-chatbot
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - qdrant